import "@/styles/globals.css";
import {Poppins} from "next/font/google";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import Footer from "@/components/Footer";
import {ThemeProvider} from "@/components/theme-provider"

const inter = Poppins({subsets: ["latin"], weight: '400'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body className={`${inter.className} min-h-screen flex flex-col`}>
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >
      <Navbar/>

      <main className="flex-grow flex">
        <aside className="hidden md:block w-[30%] border-r border-r-gray-300 dark:border-r-gray-800">
          <Sidebar/>
        </aside>

        <article className="flex-grow p-4">
          {children}
        </article>
      </main>

      <Footer/>
    </ThemeProvider>
    </body>
    </html>
  );
}
