export const SET_LOADING = 'SET_LOADING'
export const SET_DATA = 'SET_DATA'
export const SET_ERROR = 'SET_ERROR'
export const SET_SUCCESS = 'SET_SUCCESS'
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE'
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES'